### ISSUE TITLE
Cannot find module 'serverless-cljs-plugin'

### ISSUE THREAD

**Issue by ricardosllm** [nervous-systems/serverless-cljs-plugin#2]
Following the instructions on the README and the [guide](https://nervous.io/clojurescript/lambda/2017/02/06/serverless-cljs/) I get the following error: 

```
  Error --------------------------------------------------

  Cannot find module 'serverless-cljs-plugin'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module 'serverless-cljs-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:65:22)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:64:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:91:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:60:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:28)
    at <anonymous>
From previous event:
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:18:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:34:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.16.0

```

Have you seen this before?
Any ideas?

Thank you.

**Comment by moea** [comment]
@ricardosllm `lein deps` should fetch and install the npm dependencies listed in your project.clj, of which serverless-cljs-plugin ought to be a member.  I'll look into doing this implicitly, because I've seen this report a couple of times.

**Comment by ricardosllm** [comment]
Thanks @moea, confirm that `lean deps` fixes the issue.

Maybe just a note on the readme would be enough. 

closing this.
